name: Trello API Interaction

on: [push]  # Trigger the workflow on push event for any branch

jobs:
  make-curl-call:
    runs-on: ubuntu-latest  # The type of machine to run the job on

    steps:
    - name: Checkout
      uses: actions/checkout@v2  # Checks-out repository

    - name: Scrum Bot Test
      env:
        TRELLO_KEY: ${{ secrets.TRELLO_KEY }}  # Trello API key
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}  # Trello API token
      run: |
        #REQUEST_URL="https://api.trello.com/1/members/me?key=${TRELLO_KEY}&token=${TRELLO_TOKEN}"
        #curl "$REQUEST_URL"

        # Boards
        #curl "https://api.trello.com/1/members/me/boards?key=${TRELLO_KEY}&token=${TRELLO_TOKEN}"
        
        # Lists
        #BOARD_ID=6554730748de4533d808c40a
        #curl "https://api.trello.com/1/boards/${BOARD_ID}/lists?key=${TRELLO_KEY}&token=${TRELLO_TOKEN}"

        # Backlog
        LIST_ID=6554730748de4533d808c40c
        curl -s "https://api.trello.com/1/lists/${LIST_ID}/cards?key=${TRELLO_KEY}&token=${TRELLO_TOKEN}" | jq '.[].name'

        CARD_NAME="Dynamically added Card"
        TIMESTAMP=$(date)
        DESCRIPTION="This card was dynamically added, timestamp on:${TIMESTAMP}"
        curl -X POST -H "Content-Type: application/json" "https://api.trello.com/1/cards?idList=${LIST_ID}&key=${TRELLO_KEY}&token=${TRELLO_TOKEN}&name=${CARD_NAME}&desc=${DESCRIPTION}"

        echo "The End"
