name: Trello API Interaction

on: [push]  # Trigger the workflow on push event for any branch

jobs:
  make-curl-call:
    runs-on: ubuntu-latest  # The type of machine to run the job on

    steps:
    - name: Checkout
      uses: actions/checkout@v2  # Checks-out repository

    - name: Run curl command
      env:
        TRELLO_KEY: ${{ secrets.TRELLO_KEY }}  # Trello API key
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}  # Trello API token
        REQUEST_URL: "https://api.trello.com/1/members/me?key=${{TRELLO_KEY}}&token=${{TRELLO_TOKEN}}"
      run: |
        curl $REQUEST_URL
